### ISSUE TITLE
Maybe should process trees in _physics_process() instead of in _process()

### ISSUE THREAD

**Issue by berosoboy** [fian46/addons-btree#7] opened 2020-05-18 15:37 UTC
I was just wondering if it can be a better approach to process the tree on a fixed step.

**Comment by berosoboy** [comment] 2020-05-18 18:37
Another approach is let the user define it. For example:

```gdscript
# btree.gd

export(int, '_physics_process', '_process') var run_on = 0

func _physics_process(delta):
	if run_on == 0:
		tree_process(delta)
	
func _process(delta):
	if run_on == 1:
		tree_process(delta)
```

**Comment by fian46** [comment] 2020-05-19 01:28
Most of the time we use btree as decisions maker. the actual physics stuff is must decouple from ai stuff. Running ai at the same rate as physics is not necessary. If it a must to query from physics the query must perform in physics tick and saved as cached. Also Godot fixed step is not fixed at all. If you have heavy physics simulation the step maybe drop from actual step.

**Comment by berosoboy** [comment] 2020-05-19 02:13
I was wondering of it because I found a bug in the https://github.com/fian46/demo-btree.
If you walk fast at same direction that you fire, the bullet will collide with the own player.
When I tested with btree running on _physics_process () the bug doesn't happen.
But perhaps there is another way to solve this problem.

**Comment by berosoboy** [comment] 2020-05-19 02:17
What do you think about the idea of letting the user choose? We could make the option run_on = '_process' by default

**Comment by fian46** [comment] 2020-05-19 03:55
It is not a bug the implementations is not complete. But sure if you think it is necessary to give user options for choose the best setup.

**Comment by berosoboy** [comment] 2020-05-19 14:24
Submitted a PR #9

**Comment by fian46** [comment] 2020-05-20 01:05
Merged

**Closed by fian46** 2020-05-20 01:05 UTC
